package id.iswmp.padang.attendance;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;

/**
 * Replaces the MainActivity generated by `npx cap add android`.
 *
 * The plugin must be registered before super.onCreate so the bridge exposes it
 * on the first page load — the web layer calls beginObservation as soon as an
 * attendance submission starts.
 */
public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    registerPlugin(IswmpLocationIntegrityPlugin.class);
    super.onCreate(savedInstanceState);
  }
}
